### ISSUE TITLE
Is this module working in v11 ?

### ISSUE THREAD

**Issue by uniwars** [MrVauxs/speaking-as#15]
Hi, I used a script to see compatibility checks for all the modules I use before updating to V11 and it returned that this module is not compatible with v11. Is it a compatibility update issue or is the module broken in v11 ? Thank you.

**Comment by MrVauxs** [comment]
As far as I'm aware, nothing is broken on V11. Will update the manifest
though.

pon., 26 cze 2023, 12:46 użytkownik uniwars ***@***.***>
napisał:
